// <auto-generated />
namespace ProfilePort.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Sabal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sabal));
        
        string IMigrationMetadata.Id
        {
            get { return "201506202329574_Sabal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
