//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerPortalCRM
{
    using System;

    public partial class DocFee
    {
        public int ID { get; set; }
        public int MinTerm { get; set; }
        public int MaxTerm { get; set; }
        public int MaxMiles { get; set; }
        public int VehicleAge { get; set; }
        public int VehicleClass { get; set; }
        public int CreatedByID { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> Organization_ID { get; set; }
    }
}
