//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerPortalCRM
{
    using System;

    public partial class PricingBase
    {
        public int ID { get; set; }
        public int CreatedByID { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<decimal> MinBV { get; set; }
        public Nullable<decimal> MaxBV { get; set; }
        public Nullable<decimal> MinLTV { get; set; }
        public Nullable<decimal> MaxLTV { get; set; }
        public decimal PricingRateDiscount { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Organization_ID { get; set; }
    }
}
