//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.CoreLane.ScoringEngine.Models
{
    using System;

    public partial class ScoringEngineEntities : DbContext
    {
        public ScoringEngineEntities()
            : base("name=ScoringEngineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adjustment> Adjustment { get; set; }
        public virtual DbSet<AdjustmentRange> AdjustmentRange { get; set; }
        public virtual DbSet<AdjustmentType> AdjustmentType { get; set; }
        public virtual DbSet<BuyRate> BuyRate { get; set; }
        public virtual DbSet<ClassCodeAdj> ClassCodeAdj { get; set; }
        public virtual DbSet<DealerDiscount> DealerDiscount { get; set; }
        public virtual DbSet<DealerScore> DealerScore { get; set; }
        public virtual DbSet<DealerType> DealerType { get; set; }
        public virtual DbSet<DocFee> DocFee { get; set; }
        public virtual DbSet<ExcessMileage> ExcessMileage { get; set; }
        public virtual DbSet<ExpressionCatalog> ExpressionCatalog { get; set; }
        public virtual DbSet<ExpressionUsage> ExpressionUsage { get; set; }
        public virtual DbSet<ExpressionUsageDetail> ExpressionUsageDetail { get; set; }
        public virtual DbSet<PricingBase> PricingBase { get; set; }
        public virtual DbSet<StateAdjustment> StateAdjustment { get; set; }
        public virtual DbSet<StateCode> StateCode { get; set; }
        public virtual DbSet<StateFicoRange> StateFicoRange { get; set; }
        public virtual DbSet<StateMaxAPR> StateMaxAPR { get; set; }
        public virtual DbSet<TempApplicationModel> TempApplicationModel { get; set; }
        public virtual DbSet<TermCap> TermCap { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<VehicleClassType> VehicleClassType { get; set; }
        public virtual DbSet<VehicleMakeModelClass> VehicleMakeModelClass { get; set; }
        public virtual DbSet<VehicleMakeType> VehicleMakeType { get; set; }
        public virtual DbSet<VehicleModelType> VehicleModelType { get; set; }
        public virtual DbSet<ScoringEngineRun> ScoringEngineRun { get; set; }
        public virtual DbSet<TempScoreEngineResults> TempScoreEngineResults { get; set; }
        public virtual DbSet<TempScoringEngineParamLog> TempScoringEngineParamLog { get; set; }
        public virtual DbSet<TempExpressionCatalog> TempExpressionCatalog { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> GetStateMaxAPR(string stateCode, Nullable<decimal> vehicleAge, Nullable<decimal> vehicleYear, Nullable<decimal> loanTerm, Nullable<decimal> loanAmount)
        {
            var stateCodeParameter = stateCode != null ?
                new ObjectParameter("StateCode", stateCode) :
                new ObjectParameter("StateCode", typeof(string));
    
            var vehicleAgeParameter = vehicleAge.HasValue ?
                new ObjectParameter("VehicleAge", vehicleAge) :
                new ObjectParameter("VehicleAge", typeof(decimal));
    
            var vehicleYearParameter = vehicleYear.HasValue ?
                new ObjectParameter("VehicleYear", vehicleYear) :
                new ObjectParameter("VehicleYear", typeof(decimal));
    
            var loanTermParameter = loanTerm.HasValue ?
                new ObjectParameter("LoanTerm", loanTerm) :
                new ObjectParameter("LoanTerm", typeof(decimal));
    
            var loanAmountParameter = loanAmount.HasValue ?
                new ObjectParameter("LoanAmount", loanAmount) :
                new ObjectParameter("LoanAmount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetStateMaxAPR", stateCodeParameter, vehicleAgeParameter, vehicleYearParameter, loanTermParameter, loanAmountParameter);
        }
    
        public virtual int TCI_XML_IMPORT_INSERT_CREDITExtract(Nullable<int> application_ID)
        {
            var application_IDParameter = application_ID.HasValue ?
                new ObjectParameter("Application_ID", application_ID) :
                new ObjectParameter("Application_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TCI_XML_IMPORT_INSERT_CREDITExtract", application_IDParameter);
        }
    
        public virtual int TCI_XML_IMPORT_SCOREExtract_INSERT(Nullable<int> application_ID, Nullable<int> cmdid)
        {
            var application_IDParameter = application_ID.HasValue ?
                new ObjectParameter("Application_ID", application_ID) :
                new ObjectParameter("Application_ID", typeof(int));
    
            var cmdidParameter = cmdid.HasValue ?
                new ObjectParameter("cmdid", cmdid) :
                new ObjectParameter("cmdid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TCI_XML_IMPORT_SCOREExtract_INSERT", application_IDParameter, cmdidParameter);
        }
    }
}
