//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerPortalCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateCode
    {
        public StateCode()
        {
            this.DealerDiscount = new HashSet<DealerDiscount>();
            this.StateAdjustment = new HashSet<StateAdjustment>();
            this.StateMaxAPR = new HashSet<StateMaxAPR>();
            this.StateFicoRange = new HashSet<StateFicoRange>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public int SortOrder { get; set; }
        public int CreatedByID { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> Organization_ID { get; set; }
    
        public virtual ICollection<DealerDiscount> DealerDiscount { get; set; }
        public virtual ICollection<StateAdjustment> StateAdjustment { get; set; }
        public virtual ICollection<StateMaxAPR> StateMaxAPR { get; set; }
        public virtual ICollection<StateFicoRange> StateFicoRange { get; set; }
    }
}
