//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerPortalCRM
{
    using System;

    public partial class TempScoringEngineParamLog
    {
        public long ID { get; set; }
        public Nullable<long> TempScoreEngineResults_ID { get; set; }
        public string ParamName { get; set; }
        public string ParamValue { get; set; }
        public int CreatedByID { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> Organization_ID { get; set; }
    
        public virtual TempScoreEngineResults TempScoreEngineResults { get; set; }
    }
}
