//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerPortalCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempScoreEngineResults
    {
        public TempScoreEngineResults()
        {
            this.TempScoringEngineParamLog = new HashSet<TempScoringEngineParamLog>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Expression { get; set; }
        public string Result { get; set; }
        public int CreatedByID { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<long> ScoringEngineRun_ID { get; set; }
        public Nullable<int> Organization_ID { get; set; }
    
        public virtual ScoringEngineRun ScoringEngineRun { get; set; }
        public virtual ICollection<TempScoringEngineParamLog> TempScoringEngineParamLog { get; set; }
    }
}
