//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerPortalCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModelType
    {
        public VehicleModelType()
        {
            this.VehicleMakeModelClass = new HashSet<VehicleMakeModelClass>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CreatedByID { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> VehicleMakeType_ID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> Organization_ID { get; set; }
    
        public virtual ICollection<VehicleMakeModelClass> VehicleMakeModelClass { get; set; }
        public virtual VehicleMakeType VehicleMakeType { get; set; }
    }
}
