//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerPortalCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int CreatedByID { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> organization_ID { get; set; }
        public Nullable<int> VehicleMakeModelClass_ID { get; set; }
        public string DisplayName { get; set; }
    
        public virtual VehicleMakeModelClass VehicleMakeModelClass { get; set; }
    }
}
